branch-defaults:
  main:
    environment: my-discord-bot-env
environment-defaults:
  my-discord-bot-env:
    branch: main
    repository: watanabot
global:
  application_name: my-discord-bot
  default_ec2_keyname: null
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
